files:
  - source: /DiskInfo/DiskInfo/Strings/zh-CN
    translation: /DiskInfo/DiskInfo/Strings/%locale%/%original_file_name%
  - source: /DiskInfo/DiskInfo/Assets/About/About.zh-CN.md
    translation: /DiskInfo/DiskInfo/Assets/About/About.%locale%.md
